language: cpp

######################
# Operating systems
######################
os:
  - linux
  - osx


######################
# Compilers
######################
compiler:
  - gcc
  - clang


before_script:
  ######################
  # Create build directory
  ######################
  - git clone https://github.com/google/googletest
  - mkdir build
  - cd build


script:
  ######################
  # cmake and build
  ######################
  - cmake -DBUILD_TESTS=ON -DBUILD_GTEST=ON -DBUILD_FOR_COVERAGE=OFF -DCREATE_DOXYGEN_TARGET=OFF -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make test
